"""Add unique constraint to original_url

Revision ID: df6ab6b756be
Revises: 8f12f9b549b5
Create Date: 2026-04-08 12:01:12.624889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6ab6b756be'
down_revision: Union[str, Sequence[str], None] = '8f12f9b549b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'links', ['original_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='unique')
    # ### end Alembic commands ###
